### PR TITLE
Drop request as a dependency, upgrade to axios

### PR DESCRIPTION
**Pull request by SemperFortis**
All tests passed

### CODE REVIEW

**Comment by jgoralcz** [comment]
Hey @SemperFortis 

Thanks for submitting, but this causes a conflict with another PR, that handles a similar problem. See https://github.com/jgoralcz/aki-api/pull/66

I already said I was going to accept his changes, but I think that you could actually clean it up a little bit. I like your style and that style is similar to mine. 

They may be very minor differences, but I still like them nonetheless, and it's still entirely up to you.

For example:
yours: https://github.com/jgoralcz/aki-api/blob/cbe15432f646f831f8580ab849a2cb5ea6c23cfc/src/lib/functions/GetSession.js

new (if the link is dead try the develop or master branch): https://github.com/jgoralcz/aki-api/blob/cbe15432f646f831f8580ab849a2cb5ea6c23cfc/src/lib/functions/GetSession.js

So, if you wanted to clean it up you certainly can.

I'm going to accept his, then I would also like you to either resubmit yours for hacktoberfest (if that's how this works so you get credit) OR you can also pull the latest changes and then clean it up with yours and then once again you can submit this for hacktoberfest.

If you have any other questions let me know!

**Comment by SemperFortis** [comment]
Sure thing, I actually finished this a few weeks back (~2-3 weeks) but was waiting for Hacktoberfest to submit the PRs, and when I checked someone else already opened a PR.

**Comment by SemperFortis** [comment]
@jgoralcz Can you check the PR? I looked at the test and the error code isn't that helpful.

**Comment by jgoralcz** [comment]
This is most likely due to the package.json or package-lock.json file. Try getting a package.json from the `develop` branch then run another `npm install` and see if that still has a problem

**Comment by SemperFortis** [comment]
Everything's been fixed :)

**Review by jgoralcz — APPROVED** [review]
Seems you also removed the newlines at the end of the file. Not a big deal, so I'll still accept.

**Pull request merged**
