### PR TITLE
Update packages and change package

### PR DESCRIPTION
**Pull request by phamleduy04**
Hello, I'm coming to fixing some problem and this is my checklist:
- [x] Change request to Axios since Request is [deprecated](https://github.com/request/request/issues/3142) and also at #45 
- [x] Add Indonesian language at #63 
- [x] Update eslint, eslint-config-airbnb-base and eslint-plugin-import
- [x] Fix some eslint config
- [x] Test with `npm test`

image

### CODE REVIEW

**Comment by phamleduy04** [comment]
the CI won't check because of the settings of the repo, refer [this](https://circleci.com/docs/2.0/workflows/#workflows-waiting-for-status-in-github)

**Comment by jgoralcz** [comment]
Whoa this is great! I'll take a look and fix a few small things while we're at it later this week, okay?

**Comment by phamleduy04** [comment]
Sure!

**Comment by phamleduy04** [comment]
u know what, i forgot about hacktober. Can I send a pull request again lmao? I create a pull request at Sep 30th

**Comment by jgoralcz** [comment]
Sure, if that's what you need!

**Comment by phamleduy04** [comment]
ok thanks

**Comment by jgoralcz** [comment]
I was actually thinking of cleaning up some things. However, looking at it again, this is really the best way to handle the two issues without basically rewriting the whole thing. I think at some point in the future I may rewrite some of it, but this is actually the best way to handle it.

In other words, I will accept it once you make a new PR if that's what it takes for your Hacktoberfest.

Thanks again!

**Pull request closed without merging**
