### PR TITLE
Change request to axios, add indonesia, fix some err from eslint!

### PR DESCRIPTION
**Pull request by phamleduy04**

### CODE REVIEW

**Comment by phamleduy04** [comment]
image
ahhh :( would u mind to join hacktoberFest ?

**Comment by jgoralcz** [comment]
Yeah, I'm just trying to figure it out. I don't usually use GitHub, so give me a few unless you have a link I can follow lol

**Comment by jgoralcz** [comment]
Is there anything else I need to do? I added the topic

**Comment by phamleduy04** [comment]
the PR it's in review xD. Thanks a lot!

**Pull request merged**
