### PR TITLE
add badge for readme.md

### PR DESCRIPTION
**Pull request by phamleduy04**
Same as title!

### CODE REVIEW

**Comment by jgoralcz** [comment]
Ooo pretty haha. I'm thinking we should just remove ci/circleci from this project at this point. Do you want to do the honors?

**Comment by phamleduy04** [comment]
Sure! I will do it later.

**Comment by phamleduy04** [comment]
Ok I will do it now!

**Comment by phamleduy04** [comment]
Done! You need to turn off circle CI at [here](https://circleci.com/)

**Review by jgoralcz — APPROVED** [review]
thanks for adding the badge and removing circle CI

**Pull request merged**
